### ISSUE TITLE
Closed issue

### ISSUE THREAD

**Issue by jamps3** [DirtyUnicorns/android_packages_apps_Camera2#1]

**Comment by nychitman1** [comment]
For starters, we don't even support your device. Go to who you got the build from.

**Comment by nychitman1** [comment]
Also if you don't know how to logcat and you claim to be a developer -- you're likely a liar.

**Comment by Mazda--** [comment]
hahaha oh boy

**Comment by jamps3** [comment]
Ok, I got it from XDA. I'll ask there. Haven't done developing on Android much :)
Great ROM, though :) Thanks
